resources:
  containers:
  - container: mysql57
    image: mysql:5.7.24
    ports:
    - "3300:3306"
    env:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - $(pwd)/.ci/run/$NAME:/var/run/mysqld:rw
    - $(pwd)/.ci/server:/etc/mysql/conf.d:ro

variables:
  DotNetCoreSdkVersion: '2.1.700'

trigger:
  batch: false
  branches:
    include:
    - azure-pipelines

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: linux_build
    displayName: 'Linux'
    pool:
      vmimage: 'ubuntu-16.04'
    steps:
    - template: '.ci/build-steps.yml'
  - job: windows_build
    displayName: 'Windows'
    pool:
      vmimage: 'vs2017-win2016'
    steps:
    - template: '.ci/build-steps.yml'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'MySqlConnector.Tests'
        targetPath: 'tests/MySqlConnector.Tests/bin/Release/netcoreapp2.1/publish'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'SideBySide-net472'
        targetPath: 'tests/SideBySide/bin/Release/net472/publish'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'SideBySide-2.0'
        targetPath: 'tests/SideBySide/bin/Release/netcoreapp2.0/publish'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'SideBySide-2.1'
        targetPath: 'tests/SideBySide/bin/Release/netcoreapp2.1/publish'

- stage: test
  displayName: 'Test'
  dependsOn: 'build'
  jobs:
  - job: linux_test
    displayName: 'Linux'
    pool:
      vmimage: 'ubuntu-16.04'
    steps:
    - template: '.ci/mysqlconnector-tests-steps.yml'
  - job: windows_test
    displayName: 'Windows'
    pool:
      vmimage: 'vs2017-win2016'
    steps:
    - template: '.ci/mysqlconnector-tests-steps.yml'
