variables:
  DotNetCoreSdkVersion: '2.1.700'

trigger:
  batch: false
  branches:
    include:
    - azure-pipelines

jobs:
- job: linux_build
  displayName: 'Linux Build'
  pool:
    vmimage: 'ubuntu-16.04'
  steps:
  - template: '.ci/build-steps.yml'
- job: windows_build
  displayName: 'Windows Build'
  pool:
    vmimage: 'vs2017-win2016'
  steps:
  - template: '.ci/build-steps.yml'
- job: linux_unit_tests
  dependsOn: linux_build
  displayName: 'Linux Unit Tests'
  pool:
    vmimage: 'ubuntu-16.04'
  steps:
  - template: '.ci/mysqlconnector-tests-steps.yml'
- job: windows_unit_tests
  dependsOn: windows_build
  displayName: 'Windows Unit Tests'
  pool:
    vmimage: 'vs2017-win2016'
  steps:
  - template: '.ci/mysqlconnector-tests-steps.yml'
- job: linux_integration_tests
  dependsOn: linux_build
  displayName: 'Linux Tests'
  pool:
    vmimage: 'ubuntu-16.04'
  strategy:
    matrix:
      mysql56:
        image: 'mysql:5.6.44'
        unsupportedFeatures: 'Ed25519,Json,Sha256Password,RsaEncryption,LargePackets,CachingSha2Password,SessionTrack,Tls11,Tls12,UuidToBin'
      mysql57:
        image: 'mysql:5.7.26'
        unsupportedFeatures: 'Ed25519,RsaEncryption,CachingSha2Password,Tls12,UuidToBin'
  steps:
  - template: '.ci/integration-tests-steps.yml'
    parameters:
      image: $(image)
      unsupportedFeatures: $(unsupportedFeatures)
