resources:
  containers:
  - container: mysql57
    image: mysql:5.7.24
    ports:
    - "3300:3306"
    env:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - $(pwd)/.ci/run/$NAME:/var/run/mysqld:rw
    - $(pwd)/.ci/server:/etc/mysql/conf.d:ro

variables:
  DotNetCoreSdkVersion: '2.1.700'

trigger:
  batch: false
  branches:
    include:
    - azure-pipelines

jobs:
- job: linux_build
  displayName: 'Linux'
  pool:
    vmimage: 'ubuntu-16.04'
  steps:
  - template: '.ci/build-steps.yml'
- job: windows_build
  displayName: 'Windows'
  pool:
    vmimage: 'vs2017-win2016'
  steps:
  - template: '.ci/build-steps.yml'
- job: linux_unit_tests
  dependsOn: linux_build
  displayName: 'Linux Unit Tests'
  pool:
    vmimage: 'ubuntu-16.04'
  steps:
  - template: '.ci/mysqlconnector-tests-steps.yml'
- job: windows_unit_tests
  dependsOn: windows_build
  displayName: 'Windows Unit Tests'
  pool:
    vmimage: 'vs2017-win2016'
  steps:
  - template: '.ci/mysqlconnector-tests-steps.yml'
