version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: install .NET Core 6.0
          command: |
            wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            rm packages-microsoft-prod.deb
            sudo apt-get update
            sudo apt-get install -y apt-transport-https
            sudo apt-get update
            sudo apt-get install -y mariadb-client-core-10.3
            sudo apt-get install -y dotnet-sdk-6.0
            dotnet --info
      - run:
          name: start SingleStore for SideBySide tests
          command: |
            ./.circleci/setup_cluster.sh
      - run:
          name: copy config file for SideBySide tests
          command: |
            cp ./.circleci/SideBySide/config.json tests/SideBySide/config.json
            sed -i "s|ROOT_PASSWORD|${ROOT_PASSWORD}|g" tests/SideBySide/config.json
      - run:
          name: build connector
          command: |
            dotnet build -c Release
      - run:
          name: unit tests
          command: |
            cd tests/MySqlConnector.Tests
            dotnet test -f net6.0 -c Release
            cd ../../
      - run:
          name: Conformance tests
          command: |
            cd tests/Conformance.Tests/
            dotnet test -f net6.0 -c Release
            cd ../../
      - run:
          name: SideBySide tests
          command: |
            cd tests/SideBySide
            dotnet test -f net6.0 -c Release
            cd ../../

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
