name: Publish Package

on:
  push:
    branches:
    - 'master'
    paths-ignore:
    - 'docs/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:

  publish:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Unit Tests
      run: dotnet test --configuration Release tests\MySqlConnector.Tests --no-build

    - name: Pack
      run: dotnet pack --configuration Release --no-build

    - name: Install gpr tool
      run: dotnet tool install -g gpr --no-cache -v q

    - name: Publish packages
      run: gpr push --api-key ${{ secrets.GITHUB_TOKEN }} ".\**\*.nupkg"
